### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by xuxiuzhi2627** [harryhan618/SCNN_Pytorch#31]
when I train the tusimple dataset on SCNN model ,I meet the following question,could you help me ?
Traceback (most recent call last):
  File "train_tusimple.py", line 51, in <module>
    train_dataset = Dataset_Type(Dataset_Path[dataset_name], "train", transform_train)
  File "/home/chengpeisong/project/SCNN_Pytorch/dataset/Tusimple.py", line 31, in __init__
    self.createIndex()
  File "/home/chengpeisong/project/SCNN_Pytorch/dataset/Tusimple.py", line 48, in createIndex
    self.exist_list.append([int(x) for x in l[2:]])
  File "/home/chengpeisong/project/SCNN_Pytorch/dataset/Tusimple.py", line 48, in <listcomp>
    self.exist_list.append([int(x) for x in l[2:]])
ValueError: invalid literal for int() with base 10: ''

**Comment by harryhan618** [comment]
sorry just saw your post. Your information is too vague. You can try to print the `l` in your code.

**Comment by xuxiuzhi2627** [comment]
Hi，I have some question about the run time of SCNN？when I test the code，the time is 0.689，how to compute thethe run time？Is it 0.689*60？？？



---Original---
