### ISSUE TITLE
Convert model error!

### ISSUE THREAD

**Issue by ZhengXing-shawn** [harryhan618/SCNN_Pytorch#4]
Have you met the problem when converting the model from .t7 to .pth?

The report is follow:
python experiments/vgg_SCNN_DULR_w9/t7_to_pt.py
Traceback (most recent call last):
  File "experiments/vgg_SCNN_DULR_w9/t7_to_pt.py", line 9, in <module>
    model1 = load_lua('./experiments/vgg_SCNN_DULR_w9/vgg_SCNN_DULR_w9.t7', unknown_classes=True)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 608, in load_lua
    return reader.read()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 571, in read_table
    k = self.read()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 548, in read_object
    return TorchObject(cls_name, self.read())
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\ZAL\Anaconda2\envs\xz_py36\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 598, in read "corrupted.".format(typeidx))
torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id 968499410. The file maybe corrupted.

Do you know how to solve you @harryhan618 ? Thank you

**Comment by ZhengXing-shawn** [comment]
Or can you share the converted model?

**Comment by ZhengXing-shawn** [comment]
Using pytorch-0.2.0 and the error is gone. Close issue.

**Comment by harryhan618** [comment]
Pytorch-0.4.1 works fine for me. I provide the converted pth file now.
Also, there's an important change in the `model.py`. Please get updated.
